### ISSUE TITLE
not listing queries

### ISSUE THREAD

**Issue by columbian-chris** [romancandlethoughts/query-monitor-save-post-queries#4]
### Description of the bug

The queries are not being listed in Query Monitor, only a quick summary of the total number of queries:

<img width="485" src="https://github.com/user-attachments/assets/91b3f0d4-3db0-443d-b8ca-d3039704265c">

I also noticed the "Save post queries" tab is listed twice.

I know the plugin was just a beta and a lot of time has passed since last commit and a lot of changes have taken place to Query Monitor over these years, but I personally think this plugin has a lot of value so I wanted to at least throw in a bug report.

### Steps To Reproduce

Save a post, view the "Save post queries" tab in Query Monitor.

### Additional Information

Sincere thanks @jakewrfoster for creating this plugin; it is exactly what I needed where I couldn't find a solution anywhere else to benchmarking activity during a post save.

**Comment by jakewrfoster** [comment]
Hi @columbian-chris, Thank you for submitting this! I will take a look this week/weekend. As you mentioned, a lot of time has passed, but if it is helpful for you, I am happy to dig back in! I will update this issue ASAP. Thanks again!

**Comment by columbian-chris** [comment]
Awesome, @jakewrfoster!  Thank you sincerely for taking a look. 💯

**Comment by jakewrfoster** [comment]
This PR should be a fix for the issue listed above. @columbian-chris, would you mind taking doing a pull on `master` to get the latest and testing again?

Thanks! 

![image](https://github.com/user-attachments/assets/0a2ddb6c-2890-44b9-a719-cc4f921db5b8)

**Comment by columbian-chris** [comment]
This did resolve the issue for me.  Thank you so much for providing this!

**Comment by jakewrfoster** [comment]
my pleasure! I hope it's helpful!
